const defaultTheme = require('tailwindcss/defaultTheme')

module.exports = {
  content: [
    './public/*.html',
    './app/helpers/**/*.rb',
    './app/javascript/**/*.js',
    './app/views/**/*.{erb,haml,html,slim}'
  ],
	safelist: [
		'bg-slate-900',
		'bg-indigo-900',
		'bg-blue-900',
		'bg-teal-900',
		'bg-orange-900',
		'bg-red-900',
		'bg-slate-800',
		'bg-indigo-800',
		'bg-blue-800',
		'bg-teal-800',
		'bg-orange-800',
		'bg-red-800',
		'hover:bg-slate-800',
		'hover:bg-indigo-800',
		'hover:bg-blue-800',
		'hover:bg-teal-800',
		'hover:bg-orange-800',
		'hover:bg-red-800',
		'text-slate-900',
		'text-indigo-900',
		'text-blue-900',
		'text-teal-900',
		'text-orange-900',
		'text-red-900',
		'text-slate-800',
		'text-indigo-800',
		'text-blue-800',
		'text-teal-800',
		'text-orange-800',
		'text-red-800',
		'ring-slate-700',
		'ring-indigo-700',
		'ring-blue-700',
		'ring-teal-700',
		'ring-orange-700',
		'ring-red-700',
		'border-slate-800',
		'border-indigo-800',
		'border-blue-800',
		'border-teal-800',
		'border-orange-800',
		'border-red-800',
	],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter var', ...defaultTheme.fontFamily.sans],
      },
      keyframes: {
        wobble: {
          '0%': { transform: 'rotate(0deg)' },
          '20%': { transform: 'rotate(30deg)' },
          '40%': { transform: 'rotate(-30deg)' },
          '50%': { transform: 'rotate(10deg)' },
          '60%': { transform: 'rotate(-10deg)' },
          '65%': { transform: 'rotate(5deg)' },
          '70%': { transform: 'rotate(-5deg)' },
          '73%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(0deg)' },
        },
      },
      animation: {
        wiggle: 'wobble 1s linear infinite',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/aspect-ratio'),
    require('@tailwindcss/typography'),
    require('@tailwindcss/container-queries'),
  ]
}
